### ISSUE TITLE
Fix MySQL Deployment

### ISSUE THREAD

**Issue by rfrsilva** [eubr-atmosphere/tma-framework-k#15]
Fix MySQL Docker image in deployment file.
The mysql-deployment.yaml file deploys a pod with MySQL 5.6 Docker image. 
This image is not correct, because in this repository we build an image with the latest version of MySQL through this Dockerfile.

**Comment by nmsa** [comment]
@rfrsilva, please, add a bit more of information on what was the problem.

**Comment by rfrsilva** [comment]
The problem is that [mysql-deployment.yaml](https://github.com/eubr-atmosphere/tma-framework-k/blob/master/development/mysql/mysql-deployment.yaml) file deploys a pod with MySQL 5.6 Docker image. This image is not correct, because in this repository we build an image with the latest version of MySQL through this [Dockerfile](https://github.com/eubr-atmosphere/tma-framework-k/blob/master/development/mysql/Dockerfile).
